#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 29 10:34:31 2017

@author: shuchao
"""

import cPickle

output_path = "./result_hlstm/20170828_223635/results500.p"
x = cPickle.load(open(output_path,"rb"))

decoded = x[3]